# Generated by Django 5.1.6 on 2025-05-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hobby',
            options={},
        ),
        migrations.AddField(
            model_name='hobby',
            name='internal_url',
            field=models.CharField(blank=True, help_text='Например: /snowboarding/', max_length=100, null=True, verbose_name='Внутренний URL'),
        ),
    ]
