# Generated by Django 5.1.6 on 2025-05-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0002_alter_hobby_options_hobby_internal_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
